// Avisos oficiales de VELTRIX que el dueño de la cuenta puede publicar en sus comunidades de Telegram
// (con /anunciar en el chat privado con el bot). El texto es fijo: así nunca sale algo escrito a las apuradas.

export interface Announcement {
  es: string;
  en: string;
}

const APP_URL = "veltrix-trading.vercel.app/app";

export const ANNOUNCEMENTS: Record<string, Announcement> = {
  bot: {
    es: [
      "📢 <b>Nueva versión de VELTRIX: llega el BOT AUTOMÁTICO (modo simulado)</b>",
      "",
      "Actualizamos la web y la app. Lo más importante:",
      "",
      "🤖 <b>Bot automático, en modo simulado</b>",
      "Un bot que mira el mercado por vos y anota las operaciones en tu diario con la etiqueta «Bot simulado». Se enciende y se apaga con un interruptor.",
      "",
      "⚠️ Es <b>SIMULADO</b>: no usa dinero real, no toca tu exchange y no opera por vos. Sirve para medir si una estrategia funciona antes de pensar en nada más. No es asesoramiento financiero y los resultados pasados no garantizan nada.",
      "",
      "Qué podés hacer:",
      "• Elegir tu perfil: Conservador, Equilibrado, Dinámico o Lento (velas de 4 horas).",
      "• Elegir qué mira: tus activos, o además los 20 o 40 futuros cripto más operados.",
      "• Aplicar al bot las reglas de tu «Estrategia sugerida» (armada con tus propias operaciones).",
      "• Probarlo con el historial («Probar con los últimos 4 meses» y el laboratorio de variantes de 1 año). Te muestra los resultados tal cual, ganen o pierdan.",
      "• Recibir un aviso en la app y en tu Telegram cada vez que el bot abre o cierra una operación (se puede apagar).",
      "",
      "🧭 <b>Más fácil de usar</b>",
      "• Arriba de la web y de Ajustes en la app hay botones fijos para ir directo a Exchanges, Bot, Telegram, Capital y Límites.",
      "• Estrategia sugerida, ahora por cada exchange que conectaste, con un desplegable.",
      "• Exchanges compatibles (solo lectura): Binance, Bybit, MEXC, Bitunix, Gate, Bitget, OKX, KuCoin y BingX.",
      "",
      "📲 <b>Cómo actualizar la app (Android)</b>",
      `1️⃣ Entrá a ${APP_URL} y tocá Descargar.`,
      "2️⃣ Instalala encima de la versión que tenés. No perdés nada: tus operaciones están en tu cuenta.",
      "3️⃣ Si Android avisa que es un archivo de fuera de la tienda, es normal: la app no está en Google Play, se descarga directo.",
      "",
      "La web se actualiza sola: solo recargá la página.",
      "",
      "🔒 Recordatorio de seguridad: conectá tu exchange siempre con una clave de SOLO LECTURA y nunca compartas tu clave secreta con nadie.",
      "",
      "Si algo no te funciona, escribinos y lo vemos. 🙌",
    ].join("\n"),
    en: [
      "📢 <b>New VELTRIX version: the AUTOMATIC BOT arrives (simulated mode)</b>",
      "",
      "We updated the web and the app. The highlights:",
      "",
      "🤖 <b>Automatic bot, in simulated mode</b>",
      "A bot that watches the market for you and logs trades in your journal tagged “Simulated bot”. You turn it on and off with a switch.",
      "",
      "⚠️ It is <b>SIMULATED</b>: no real money, it doesn't touch your exchange and it doesn't trade for you. It's there to measure whether a strategy works before thinking about anything else. Not financial advice, and past results guarantee nothing.",
      "",
      "What you can do:",
      "• Pick your profile: Conservative, Balanced, Dynamic or Slow (4-hour candles).",
      "• Pick what it watches: your assets, or also the 20 or 40 most traded crypto futures.",
      "• Apply the rules from your “Suggested strategy” (built from your own trades) to the bot.",
      "• Test it on history (“Test with the last 4 months” and the 1-year variant lab). It shows the results as they are, win or lose.",
      "• Get an alert in the app and on your Telegram each time the bot opens or closes a trade (can be turned off).",
      "",
      "🧭 <b>Easier to use</b>",
      "• Fixed shortcut buttons at the top of the web and of Settings in the app take you straight to Exchanges, Bot, Telegram, Capital and Limits.",
      "• Suggested strategy, now per connected exchange, with a dropdown.",
      "• Supported exchanges (read-only): Binance, Bybit, MEXC, Bitunix, Gate, Bitget, OKX, KuCoin and BingX.",
      "",
      "📲 <b>How to update the app (Android)</b>",
      `1️⃣ Go to ${APP_URL} and tap Download.`,
      "2️⃣ Install it over the version you have. You lose nothing: your trades live in your account.",
      "3️⃣ If Android warns that it's a file from outside the store, that's normal: the app isn't on Google Play, it's downloaded directly.",
      "",
      "The web updates by itself: just reload the page.",
      "",
      "🔒 Security reminder: always connect your exchange with a READ-ONLY key and never share your secret key with anyone.",
      "",
      "If something doesn't work, write to us and we'll look into it. 🙌",
    ].join("\n"),
  },
  novedades: {
    es: [
      "🚀 <b>NOVEDADES DE VELTRIX</b> 🚀",
      "",
      "Esta semana llegó un montón. Mirá 👇",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "📱 <b>APP ANDROID 1.4.0</b>",
      `Descargala en <b>${APP_URL.replace("/app", "")}</b> → menú «Descargar».`,
      "👉 Instalala encima de la que ya tenés: <b>no perdés nada</b>.",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "🤖 <b>BOT AUTOMÁTICO, CON MUCHOS MÁS ACTIVOS</b>",
      "Elegí hasta <b>10 activos</b> desde una lista desplegable:",
      "🥇 Oro · 🥈 Plata · 🛢 Petróleo",
      "📈 Acciones: MSTR, NVDA, TSLA, COIN y más",
      "🪙 Y decenas de criptos: BTC, ETH, SOL, ENA…",
      "Por defecto opera en <b>modo simulado, sin plata real</b>.",
      "",
      "🎬 Además hay un <b>video de 2 minutos</b> que explica cómo funciona, paso a paso. Está arriba de la pantalla del bot, en la web y en la app.",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "💱 <b>BOT CON DINERO REAL (OPCIONAL)</b>",
      "Elegí tu exchange: Binance, Bybit, OKX, Bitget, BingX, Gate, KuCoin o Bitunix.",
      "🛡 Topes de seguridad",
      "🧪 Prueba en seco primero",
      "🚨 Botón de pánico",
      "Hoy solo <b>Bitunix</b> está probado con operaciones reales. Si probás otro y algo falla, avisanos 🙏",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "💬 <b>NUEVO EN EL BOT DE TELEGRAM</b>",
      "Escribilos en el grupo:",
      "📍 <code>/niveles BTC</code> → precio, RSI y tendencia al instante",
      "🧮 <code>/calc 65000 64500 1000 1</code> → cuánto comprar según tu riesgo",
      "🏆 <code>/semana</code> → el ranking de la semana",
      "📊 <code>/grafico BTC 4h</code> → gráfico de velas",
      "",
      "Y además, automático:",
      "☀️ Resumen del mercado cada mañana",
      "💸 Avisos cuando el funding se dispara o hay movimientos fuertes",
      "👍👎 Votá en cada señal si la tomás o la pasás",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "⚠️ <i>Herramienta de práctica y estudio. No es consejo de inversión ni garantiza ganancias. Cada persona opera bajo su propia responsabilidad. Con dinero real arriesgás plata de verdad: usalo solo con plata que puedas perder.</i>",
    ].join("\n"),
    en: [
      "🚀 <b>WHAT'S NEW IN VELTRIX</b> 🚀",
      "",
      "A lot landed this week. Take a look 👇",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "📱 <b>ANDROID APP 1.4.0</b>",
      `Download it at <b>${APP_URL.replace("/app", "")}</b> → “Download” menu.`,
      "👉 Install it over the one you already have: <b>you lose nothing</b>.",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "🤖 <b>AUTOMATIC BOT, WITH MANY MORE ASSETS</b>",
      "Pick up to <b>10 assets</b> from a dropdown list:",
      "🥇 Gold · 🥈 Silver · 🛢 Oil",
      "📈 Stocks: MSTR, NVDA, TSLA, COIN and more",
      "🪙 And dozens of cryptos: BTC, ETH, SOL, ENA…",
      "By default it runs in <b>simulated mode, with no real money</b>.",
      "",
      "🎬 There is also a <b>2-minute video</b> explaining how it works, step by step. It's above the bot screen, on the web and in the app.",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "💱 <b>BOT WITH REAL MONEY (OPTIONAL)</b>",
      "Choose your exchange: Binance, Bybit, OKX, Bitget, BingX, Gate, KuCoin or Bitunix.",
      "🛡 Safety limits",
      "🧪 Dry run first",
      "🚨 Panic button",
      "Today only <b>Bitunix</b> has been tested with real trades. If you try another one and something fails, let us know 🙏",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "💬 <b>NEW IN THE TELEGRAM BOT</b>",
      "Type these in the group:",
      "📍 <code>/levels BTC</code> → price, RSI and trend instantly",
      "🧮 <code>/calc 65000 64500 1000 1</code> → how much to buy for your risk",
      "🏆 <code>/week</code> → this week's ranking",
      "📊 <code>/chart BTC 4h</code> → candlestick chart",
      "",
      "And automatically:",
      "☀️ Market summary every morning",
      "💸 Alerts when funding spikes or there are strong moves",
      "👍👎 Vote on each signal: are you taking it or passing?",
      "",
      "━━━━━━━━━━━━━━━",
      "",
      "⚠️ <i>Practice and study tool. Not investment advice and no guarantee of profit. Everyone trades at their own responsibility. With real money you risk real money: only use what you can afford to lose.</i>",
    ].join("\n"),
  },
};

export const announcementIds = () => Object.keys(ANNOUNCEMENTS);
