// Traducciones al inglés (generado). Clave = texto original en español.
export const EN: Record<string, string> = {
  "mejor": "best",
  "peor": "worst",
  "abiertas": "open",
  "cerradas": "closed",
  "balance": "balance",
  "{sym} cerrada en {out} · {r}R": "{sym} closed at {out} · {r}R",
  "¿Querés registrar la operación igual?": "Do you want to log the trade anyway?",
  "Operación registrada: {sym} {dir} @ {entry}": "Trade logged: {sym} {dir} @ {entry}",
  "{n} operaciones registradas en el diario.": "{n} trades logged in the journal.",
  "{sym} cerrada en Break Even · 0R": "{sym} closed at Break Even · 0R",
  "{sym} cerrada manualmente · {r}R": "{sym} closed manually · {r}R",
  "Cierre automático:": "Auto-close:",
  "VELTRIX sigue el precio (criptomonedas) y marca TP o SL solo cuando el precio los toca. Si una misma vela toca ambos, se toma SL.": "VELTRIX follows the price (crypto) and marks TP or SL only when the price hits them. If one candle hits both, SL is used.",
  "(plan con webhooks): pegá la URL en \"Webhook URL\" de la alerta.": "(webhook plan): paste the URL into the alert's \"Webhook URL\" field.",
  "Telegram, WhatsApp o Discord:": "Telegram, WhatsApp or Discord:",
  "copiá el mensaje de la señal y pegalo en \"Registrar → Pegar señal\". Lo interpreta solo.": "copy the signal message and paste it into \"Log → Paste signal\". It's parsed automatically.",
  "Zapier, Make o n8n:": "Zapier, Make or n8n:",
  "usá la acción \"Webhooks → POST\" hacia esta URL con el texto de la señal como cuerpo.": "use the \"Webhooks → POST\" action to this URL with the signal text as the body.",
  "Bots y plataformas propias:": "Bots and your own platforms:",
  "un POST con JSON, por ejemplo": "a POST with JSON, for example",
  "A mano:": "By hand:",
  "\"Registrar → Manual\".": "\"Log → Manual\".",
  "Cargá tu primera señal": "Log your first signal",
  "Pegá un mensaje de Telegram o WhatsApp en \"Registrar operación\", o cargala a mano.": "Paste a Telegram or WhatsApp message into \"Log trade\", or enter it by hand.",
  "Conectá tu fuente": "Connect your source",
  "Abajo, en \"Conectá tu fuente de señales\", copiá tu URL personal para TradingView u otras herramientas.": "Below, in \"Connect your signal source\", copy your personal URL for TradingView or other tools.",
  "Mirá tus resultados": "Watch your results",
  "VELTRIX calcula tu R neto, acierto y curva de capital. El cierre de TP y SL puede ser automático.": "VELTRIX calculates your net R, win rate and equity curve. TP and SL closing can be automatic.",
  "CONECTÁ TU FUENTE DE SEÑALES": "CONNECT YOUR SIGNAL SOURCE",
  "VELTRIX es una herramienta de registro y no constituye asesoramiento financiero ni recomendación de inversión. Operar en mercados financieros implica riesgo de pérdida. Los resultados pasados no garantizan resultados futuros. No está afiliado a TradingView.": "VELTRIX is a record-keeping tool and is not financial advice or an investment recommendation. Trading financial markets involves risk of loss. Past results do not guarantee future results. Not affiliated with TradingView.",
  "tu diario se sincroniza en la nube entre web y móvil.": "your journal syncs in the cloud between web and mobile.",
  "VELTRIX · cuando cierres operaciones, el ticker de resultados corre acá": "VELTRIX · when you close trades, the results ticker runs here",
  "Enviá tus señales a esta URL, vengan de donde vengan": "Send your signals to this URL, wherever they come from",
  "¿Desde dónde puedo enviar señales?": "Where can I send signals from?",
  "Confirmar: la URL actual dejará de funcionar": "Confirm: the current URL will stop working",
  "Regenerar URL del webhook": "Regenerate webhook URL",
  "BIENVENIDO A VELTRIX": "WELCOME TO VELTRIX",
  "Empezá en tres pasos.": "Get started in three steps.",
  "Entendido": "Got it",
  "Diario de trading · En vivo": "Trading journal · Live",
  "Comunidad": "Community",
  "Compartir": "Share",
  "Exportar CSV": "Export CSV",
  "Salir": "Sign out",
  "Cargando diario…": "Loading journal…",
  "Confirmar: eliminar cuenta y todos mis datos": "Confirm: delete account and all my data",
  "Eliminar mi cuenta": "Delete my account",
  "Confirmar borrado total": "Confirm delete everything",
  "Borrar diario": "Clear journal",
  "Términos": "Terms",
  "Privacidad": "Privacy",
  "Eliminar datos": "Delete data",
  "R neto acumulado": "Cumulative net R",
  "Acierto": "Win rate",
  "Profit factor": "Profit factor",
  "ganancia / pérdida": "profit / loss",
  "R promedio": "Average R",
  "por operación cerrada": "per closed trade",
  "Operaciones": "Trades",
  "Cierre automático activado.": "Auto-close enabled.",
  "Cierre automático desactivado.": "Auto-close disabled.",
  "No se pudo guardar el cambio.": "Couldn't save the change.",
  "URL regenerada. Actualizala en tus alertas de TradingView: la anterior dejó de funcionar.": "URL regenerated. Update it in your TradingView alerts: the old one no longer works.",
  "No se pudo regenerar la URL.": "Couldn't regenerate the URL.",
  "No se pudo obtener la URL.": "Couldn't get the URL.",
  "URL de webhook copiada al portapapeles.": "Webhook URL copied to the clipboard.",
  "No se pudo copiar automáticamente — seleccioná el texto a mano.": "Couldn't copy automatically — select the text by hand.",
  "No se pudo eliminar la cuenta.": "Couldn't delete the account.",
  "Límites guardados.": "Limits saved.",
  "No se pudieron guardar los límites.": "Couldn't save the limits.",
  "Capital guardado.": "Capital saved.",
  "No se pudo guardar el capital.": "Couldn't save the capital.",
  "No se pudo registrar la operación.": "Couldn't log the trade.",
  "No se pudo cerrar la operación.": "Couldn't close the trade.",
  "Operación reabierta.": "Trade reopened.",
  "No se pudo reabrir la operación.": "Couldn't reopen the trade.",
  "Operación eliminada del diario.": "Trade removed from the journal.",
  "No se pudo eliminar la operación.": "Couldn't delete the trade.",
  "Notas guardadas.": "Notes saved.",
  "No se pudieron guardar las notas.": "Couldn't save the notes.",
  "17 operaciones de ejemplo cargadas — explorá el diario.": "17 sample trades loaded — explore the journal.",
  "No se pudieron cargar los datos de ejemplo.": "Couldn't load the sample data.",
  "CSV exportado — compatible con Excel y Google Sheets.": "CSV exported — compatible with Excel and Google Sheets.",
  "Diario borrado por completo.": "Journal cleared.",
  "No se pudo borrar el diario.": "Couldn't clear the journal.",
  "Cuenta creada. Si tu proyecto pide confirmación por email, revisá tu bandeja de entrada.": "Account created. If email confirmation is required, check your inbox.",
  "No se pudo completar la operación.": "Couldn't complete the operation.",
  "Ingresá tu email arriba y volvé a tocar el link.": "Enter your email above and tap the link again.",
  "Te enviamos un email para restablecer tu contraseña.": "We sent you an email to reset your password.",
  "No se pudo enviar el email.": "Couldn't send the email.",
  "Te reenviamos el email de confirmación.": "We resent the confirmation email.",
  "No se pudo reenviar el email.": "Couldn't resend the email.",
  "Ingresar": "Sign in",
  "Crear cuenta": "Create account",
  "Contraseña": "Password",
  "vos@ejemplo.com": "you@example.com",
  "Ocultar": "Hide",
  "Ver": "Show",
  "¿Olvidaste tu contraseña?": "Forgot your password?",
  "Reenviar confirmación": "Resend confirmation",
  "términos de uso": "terms of use",
  "política de privacidad": "privacy policy",
  "Acepto los": "I accept the",
  "y la": "and the",
  "Un momento…": "One moment…",
  "✈ Unite a la comunidad de VELTRIX en Telegram": "✈ Join the VELTRIX community on Telegram",
  "VELTRIX es una herramienta de registro, no brinda asesoramiento financiero. Operar implica riesgo de pérdida. No está afiliado a TradingView.": "VELTRIX is a record-keeping tool and does not provide financial advice. Trading involves risk of loss. Not affiliated with TradingView.",
  "Contraseña actualizada — ingresá con tu nueva contraseña.": "Password updated — sign in with your new password.",
  "No se pudo actualizar la contraseña.": "Couldn't update the password.",
  "Nueva contraseña": "New password",
  "Elegí una contraseña nueva": "Choose a new password",
  "Contraseña nueva": "New password",
  "Guardar contraseña": "Save password",
  "«{label}» — falta el símbolo.": "«{label}» — symbol is missing.",
  "«{label}» — dirección «{dir}» no reconocida (usá COMPRA/VENTA, BUY/SELL o LONG/SHORT).": "«{label}» — direction «{dir}» not recognized (use BUY/SELL or LONG/SHORT).",
  "«{label}» — entrada, TP y SL deben ser números válidos.": "«{label}» — entry, TP and SL must be valid numbers.",
  "El mensaje está vacío.": "The message is empty.",
  "No encontré el activo (ej: BTCUSDT, BTC/USDT o #BTC).": "Couldn't find the asset (e.g. BTCUSDT, BTC/USDT or #BTC).",
  "No encontré el precio de entrada (ej: «Entrada: 65000»).": "Couldn't find the entry price (e.g. “Entry: 65000”).",
  "No encontré el take profit (ej: «TP: 66500»).": "Couldn't find the take profit (e.g. “TP: 66500”).",
  "No encontré el stop loss (ej: «SL: 64500»).": "Couldn't find the stop loss (e.g. “SL: 64500”).",
  "No pude saber si es compra o venta (usá LONG/SHORT o COMPRA/VENTA).": "Couldn't tell if it's a buy or a sell (use LONG/SHORT or BUY/SELL).",
  "Los niveles no coinciden con una compra (TP arriba y SL abajo). Revisá el mensaje.": "The levels don't match a buy (TP above, SL below). Check the message.",
  "Los niveles no coinciden con una venta (TP abajo y SL arriba). Revisá el mensaje.": "The levels don't match a sell (TP below, SL above). Check the message.",
  "Pegá al menos una línea de alerta.": "Paste at least one alert line.",
  "JSON inválido: cada alerta debe ser un objeto.": "Invalid JSON: each alert must be an object.",
  "El JSON no es válido (revisá comillas y comas).": "The JSON isn't valid (check quotes and commas).",
  "«{line}» — se esperan 6 campos separados por |": "«{line}» — expected 6 fields separated by |",
  "Domingo": "Sunday",
  "Lunes": "Monday",
  "Martes": "Tuesday",
  "Miércoles": "Wednesday",
  "Jueves": "Thursday",
  "Viernes": "Friday",
  "Sábado": "Saturday",
  "Compras": "Buys",
  "Ventas": "Sells",
  "Tu mejor activo es {sym} ({r} en {n} operaciones).": "Your best asset is {sym} ({r} over {n} trades).",
  "Tu activo más costoso es {sym} ({r}). Pensá si conviene seguir operándolo.": "Your costliest asset is {sym} ({r}). Consider whether it's worth continuing to trade it.",
  "Tu mejor día es el {day} ({r}).": "Your best day is {day} ({r}).",
  "Tu peor día es el {day} ({r}).": "Your worst day is {day} ({r}).",
  "Operás mejor entre {h} ({r}).": "You trade best between {h} ({r}).",
  "Evitá operar entre {h}: ahí perdés {r}.": "Avoid trading between {h}: you lose {r} there.",
  "Te va mejor en {a} ({ra}) que en {b} ({rb}).": "You do better on {a} ({ra}) than on {b} ({rb}).",
  "Alcanzaste tu pérdida máxima del día ({n}R). Hoy no operes más.": "You hit your maximum daily loss ({n}R). Don't trade any more today.",
  "Estás cerca de tu pérdida máxima del día: llevás {a}R de −{b}R.": "You're close to your maximum daily loss: you're at {a}R of −{b}R.",
  "Llegaste al máximo de {n} operaciones de hoy.": "You've reached today's maximum of {n} trades.",
  "Llevás {a} de {b} operaciones permitidas hoy.": "You've made {a} of {b} trades allowed today.",
  "Todo el historial": "All history",
  "Últimos 7 días": "Last 7 days",
  "El TP está del lado equivocado: en una compra debe estar arriba de la entrada.": "The TP is on the wrong side: on a buy it must be above the entry.",
  "El TP está del lado equivocado: en una venta debe estar abajo de la entrada.": "The TP is on the wrong side: on a sell it must be below the entry.",
  "Arriesgás más del 5 % por operación: es un riesgo muy alto.": "You're risking more than 5% per trade: that's very high risk.",
  "Lo habitual es arriesgar entre 0,5 % y 2 % por operación.": "The usual range is risking 0.5% to 2% per trade.",
  "Necesitás más margen ({m}) que tu capital. Bajá el riesgo, acercá el stop o subí el apalancamiento.": "You need more margin ({m}) than your capital. Lower the risk, tighten the stop or raise the leverage.",
  "La posición vale más que tu capital: solo podés hacerla con apalancamiento.": "The position is worth more than your capital: you can only take it with leverage.",
  "La relación riesgo/beneficio es menor a 1:1.": "The risk/reward ratio is below 1:1.",
  "Fecha": "Date",
  "Activo": "Asset",
  "Direccion": "Direction",
  "Entrada": "Entry",
  "Estado": "Status",
  "Salida": "Exit",
  "Notas": "Notes",
  "Etiquetas": "Tags",
  "Emoción": "Emotion",
  "Ejecución": "Execution",
  "Setup": "Setup",
  "Calma": "Calm",
  "Confianza": "Confidence",
  "Miedo": "Fear",
  "Codicia": "Greed",
  "FOMO": "FOMO",
  "Venganza": "Revenge",
  "Ansiedad": "Anxiety",
  "Seguí el plan": "Followed the plan",
  "Sin plan": "No plan",
  "Entré tarde": "Entered late",
  "Moví el stop": "Moved the stop",
  "Cerré antes": "Closed early",
  "Sin stop": "No stop",
  "Sobreoperé": "Overtraded",
  "Señal de comunidad": "Community signal",
  "Breakout": "Breakout",
  "Reversión": "Reversal",
  "Tendencia": "Trend",
  "Noticia": "News",
  "En Binance: Perfil → Gestión de API → Crear API → \"Generada por el sistema\".": "On Binance: Profile → API Management → Create API → \"System generated\".",
  "Ponele un nombre (por ejemplo VELTRIX) y confirmá.": "Give it a name (for example VELTRIX) and confirm.",
  "Dejá tildado SOLO \"Habilitar lectura\". No actives retiros, trading spot/margen ni transferencias.": "Leave ONLY \"Enable Reading\" ticked. Don't enable withdrawals, spot/margin trading or transfers.",
  "En restricciones de IP elegí \"Sin restricciones\" (con solo lectura es seguro).": "Under IP restrictions choose \"Unrestricted\" (it's safe with read-only).",
  "Copiá la API Key y la Secret Key y pegalas acá. La Secret se muestra una sola vez.": "Copy the API Key and the Secret Key and paste them here. The Secret is shown only once.",
  "En Bybit: Perfil → API → Crear nueva clave → \"Claves generadas por el sistema\".": "On Bybit: Profile → API → Create New Key → \"System-generated API Keys\".",
  "Ponele un nombre (por ejemplo VELTRIX) y elegí permisos \"Solo lectura\".": "Give it a name (for example VELTRIX) and choose \"Read-Only\" permissions.",
  "Activá la lectura de \"Contratos → Órdenes y posiciones\". No actives billetera ni retiros.": "Enable reading for \"Contracts → Orders & Positions\". Don't enable wallet or withdrawals.",
  "Dejá la restricción de IP en \"Sin restricción de IP\" (con solo lectura es seguro).": "Leave IP restriction as \"No IP restriction\" (it's safe with read-only).",
  "Copiá la API Key y la Secret y pegalas acá. La Secret se muestra una sola vez.": "Copy the API Key and the Secret and paste them here. The Secret is shown only once.",
  "No se pudo conectar.": "Couldn't connect.",
  "{name} conectado. Operaciones importadas: {n}.": "{name} connected. Trades imported: {n}.",
  "No se pudo sincronizar.": "Couldn't sync.",
  "Sincronizado: {n} operaciones nuevas.": "Synced: {n} new trades.",
  "Todo al día: no hay operaciones nuevas.": "All up to date: no new trades.",
  "{name} desconectado. Se borró la clave guardada.": "{name} disconnected. The stored key was deleted.",
  "No se pudo desconectar.": "Couldn't disconnect.",
  "CONECTAR EXCHANGE": "CONNECT EXCHANGE",
  "Traé tus operaciones automáticamente · solo lectura": "Bring in your trades automatically · read-only",
  "Conectado": "Connected",
  "Con error": "Error",
  "Última sincronización: {when} · {n} nuevas": "Last sync: {when} · {n} new",
  "Todavía sin sincronizar": "Not synced yet",
  "Confirmar: borrar la clave": "Confirm: delete the key",
  "Desconectar": "Disconnect",
  "Conectá Binance o Bybit con una clave de solo lectura y VELTRIX trae tus operaciones cerradas al diario, sin copiarlas a mano.": "Connect Binance or Bybit with a read-only key and VELTRIX brings your closed trades into the journal, no copying by hand.",
  "Sincronizar ahora": "Sync now",
  "Antes cargá tu capital y el % de riesgo en \"Capital y dinero\": se usan para convertir tus resultados a R.": "First enter your capital and risk % in \"Capital and money\": they're used to convert your results to R.",
  "Cómo crear la clave (solo lectura)": "How to create the key (read-only)",
  "Clave secreta (Secret)": "Secret key (Secret)",
  "Verificando…": "Verifying…",
  "Conectar {name}": "Connect {name}",
  "Tu clave secreta se guarda cifrada en el servidor y no se vuelve a mostrar. VELTRIX solo lee: rechaza claves que permitan operar o retirar. Las operaciones se importan con tu 1R (capital × riesgo %) y quedan marcadas con el exchange de origen.": "Your secret key is stored encrypted on the server and never shown again. VELTRIX only reads: it rejects keys that allow trading or withdrawing. Trades are imported using your 1R (capital × risk %) and are tagged with the exchange they came from.",
  "No se pudo comunicar con el servidor. Probá de nuevo en unos minutos.": "Couldn't reach the server. Try again in a few minutes.",
  "Importada de {name}": "Imported from {name}",
  "Se borra la clave guardada de {name}. Las operaciones ya importadas quedan en tu diario.": "The stored key for {name} will be deleted. Trades already imported stay in your journal.",
  "El portapapeles está vacío.": "The clipboard is empty.",
  "Tu navegador bloqueó el acceso al portapapeles — pegá el texto manualmente (Ctrl+V).": "Your browser blocked clipboard access — paste the text manually (Ctrl+V).",
  "Ingresá el símbolo (ej: BTCUSDT).": "Enter the symbol (e.g. BTCUSDT).",
  "Entrada inválida.": "Invalid entry.",
  "TP inválido.": "Invalid TP.",
  "SL inválido.": "Invalid SL.",
  "El SL no puede ser igual a la entrada.": "SL can't be equal to the entry.",
  "En LONG el TP debe estar arriba de la entrada y el SL abajo.": "For a LONG, TP must be above the entry and SL below.",
  "En SHORT el TP debe estar abajo de la entrada y el SL arriba.": "For a SHORT, TP must be below the entry and SL above.",
  "Elegí fecha y hora.": "Pick a date and time.",
  "REGISTRAR OPERACIÓN": "LOG TRADE",
  "Pegá una señal de cualquier fuente o cargala a mano": "Paste a signal from any source or enter it by hand",
  "Pegar señal": "Paste signal",
  "Manual": "Manual",
  "Pegá una señal de cualquier fuente, por ejemplo:\n#BTC/USDT LONG\nEntry: 65000\nTP: 66500\nSL: 64500\n\nO en formato simple:\n": "Paste a signal from any source, for example:\n#BTC/USDT LONG\nEntry: 65000\nTP: 66500\nSL: 64500\n\nOr in simple format:\n",
  "Interpretar": "Parse",
  "Desde portapapeles": "From clipboard",
  "Ejemplo": "Example",
  "Confirmar": "Confirm",
  "operación": "trade",
  "operaciones": "trades",
  "Funciona con mensajes de Telegram, WhatsApp o Discord, alertas de cualquier plataforma o tu propio formato (": "Works with Telegram, WhatsApp or Discord messages, alerts from any platform, or your own format (",
  ", JSON). Revisá lo que entendió antes de confirmar.": ", JSON). Check what it understood before confirming.",
  "Dirección": "Direction",
  "Take Profit": "Take Profit",
  "Stop Loss": "Stop Loss",
  "Fecha y hora": "Date and time",
  "(opcional — setup, confluencia, emoción)": "(optional — setup, confluence, emotion)",
  "OB de H1 + FVG, sesión NY…": "H1 OB + FVG, NY session…",
  "R:R planificado": "Planned R:R",
  "Riesgo 1 : Beneficio —": "Risk 1 : Reward —",
  "Riesgo 1 : Beneficio {rr}": "Risk 1 : Reward {rr}",
  "Añadir al diario": "Add to journal",
  "Funciona con cualquier indicador. Elegí la dirección y escribí en TP y SL lo que tu indicador entrega (un {plot} de TradingView o un número fijo). Copiá el mensaje en el campo \"Mensaje\" de la alerta.": "Works with any indicator. Choose the direction and type in TP and SL what your indicator provides (a {plot} from TradingView or a fixed number). Copy the message into the alert's \"Message\" field.",
  "Formato simple": "Simple format",
  "Formato JSON": "JSON format",
  "ahora": "now",
  "hace {n} min": "{n} min ago",
  "hace {n} h": "{n} h ago",
  "hace {n} d": "{n} d ago",
  "Copiar mensaje": "Copy message",
  "¡Copiado!": "Copied!",
  "Copiar": "Copy",
  "Take profit": "Take profit",
  "Error": "Error",
  "No se pudo guardar.": "Couldn't save.",
  "Frená por hoy": "Stop for today",
  "No": "No",
  "Registrar igual": "Log anyway",
  "Faltan datos": "Missing data",
  "Completá símbolo, entrada, TP y SL con números válidos.": "Fill in symbol, entry, TP and SL with valid numbers.",
  "No se pudo cargar el ejemplo.": "Couldn't load the sample.",
  "Detectamos una señal en tu portapapeles": "We detected a signal in your clipboard",
  "Tocá para usarla": "Tap to use it",
  "Pegar": "Paste",
  "Funciona con mensajes de Telegram, WhatsApp o Discord, alertas de cualquier plataforma o tu propio formato. Revisá lo que entendió antes de confirmar.": "Works with Telegram, WhatsApp or Discord messages, alerts from any platform, or your own format. Check what it understood before confirming.",
  "SÍMBOLO": "SYMBOL",
  "COMPRA": "BUY",
  "VENTA": "SELL",
  "ENTRADA": "ENTRY",
  "TAKE PROFIT": "TAKE PROFIT",
  "STOP LOSS": "STOP LOSS",
  "Guardar operación": "Save trade",
  "Cargar operaciones de ejemplo": "Load sample trades",
  "Señales": "Signals",
  "Diario": "Journal",
  "Registrar": "Log",
  "Riesgo": "Risk",
  "Ajustes": "Settings",
  "EN VIVO": "LIVE",
  "Tenés que aceptar los términos de uso y la política de privacidad.": "You must accept the terms of use and the privacy policy.",
  "Te enviamos un email. Abrí el link desde el navegador (no desde Gmail directamente) para crear tu nueva contraseña en la web.": "We sent you an email. Open the link from your browser (not directly from Gmail) to create your new password on the web.",
  "DIARIO DE TRADING · EN VIVO": "TRADING JOURNAL · LIVE",
  "ELEGÍ UNA CONTRASEÑA NUEVA": "CHOOSE A NEW PASSWORD",
  "Bienvenido a VELTRIX": "Welcome to VELTRIX",
  "Tu diario de trading con señales en vivo. Registrá cada operación y mirá tus resultados en R, tu curva de capital y tu evolución mes a mes.": "Your trading journal with live signals. Log every trade and see your results in R, your equity curve and your month-by-month progress.",
  "Estadísticas claras: acierto, profit factor y R promedio": "Clear stats: win rate, profit factor and average R",
  "Todo sincronizado entre la app y la web": "Everything synced between the app and the web",
  "Recibí señales de donde quieras": "Get signals from anywhere",
  "No importa qué plataforma uses. VELTRIX entiende tus señales sin complicarte.": "It doesn't matter which platform you use. VELTRIX understands your signals without hassle.",
  "TradingView u otra herramienta: pegá tu URL personal (Ajustes)": "TradingView or another tool: paste your personal URL (Settings)",
  "Telegram o WhatsApp: copiá el mensaje y pegalo en Registrar": "Telegram or WhatsApp: copy the message and paste it in Log",
  "O cargalas a mano en un minuto": "Or enter them by hand in a minute",
  "Que no se te escape ninguna": "Don't miss a single one",
  "Activá las notificaciones para enterarte al instante cuando llega una señal o cuando se toca tu TP o SL.": "Turn on notifications to know instantly when a signal arrives or your TP or SL is hit.",
  "Cierre automático de TP y SL (criptomonedas)": "Automatic TP and SL closing (crypto)",
  "Podés apagarlo cuando quieras en Ajustes": "You can turn it off anytime in Settings",
  "Activar notificaciones y empezar": "Turn on notifications and start",
  "Siguiente": "Next",
  "Ahora no": "Not now",
  "Saltar": "Skip",
  "Acumulado": "Cumulative",
  "en": "in",
  "CURVA DE CAPITAL (R)": "EQUITY CURVE (R)",
  "RESULTADO NETO": "NET RESULT",
  "RESUMEN MENSUAL": "MONTHLY SUMMARY",
  "⛔ FRENÁ POR HOY": "⛔ STOP FOR TODAY",
  "⚠ CUIDADO CON TU LÍMITE DIARIO": "⚠ WATCH YOUR DAILY LIMIT",
  "ANÁLISIS": "ANALYSIS",
  "Mejor racha": "Best streak",
  "Peor racha": "Worst streak",
  "Racha actual": "Current streak",
  "ganadas": "won",
  "perdidas": "lost",
  "Día": "Day",
  "Hora": "Hour",
  "RESULTADO POR ETIQUETA": "RESULT BY TAG",
  "ops": "trades",
  "Precio inválido": "Invalid price",
  "Ingresá un precio de salida válido.": "Enter a valid exit price.",
  "Cerrar": "Close",
  "a mercado": "at market",
  "Precio de salida": "Exit price",
  "Cancelar": "Cancel",
  "Guardar": "Save",
  "Notas y etiquetas": "Notes and tags",
  "¿Qué pasó en esta operación?": "What happened in this trade?",
  "Por qué entraste, cómo te sentiste, qué aprendiste…": "Why you entered, how you felt, what you learned…",
  "ETIQUETA PROPIA": "CUSTOM TAG",
  "Ej: Apertura de Nueva York": "E.g. New York open",
  "Agregar": "Add",
  "etiquetas": "tags",
  "Eliminar operación": "Delete trade",
  "¿Borrar {sym} del diario?": "Delete {sym} from the journal?",
  "Borrar": "Delete",
  "No se pudo eliminar.": "Couldn't delete.",
  "⚡ Cerrada automáticamente": "⚡ Closed automatically",
  "Tocó TP": "TP hit",
  "Tocó SL": "SL hit",
  "Calcular": "Calculate",
  "Reabrir": "Reopen",
  "Comunidad de VELTRIX": "VELTRIX Community",
  "Sumate en Telegram: señales, ideas y otros traders.": "Join us on Telegram: signals, ideas and other traders.",
  "Unirme ›": "Join ›",
  "ABIERTA": "OPEN",
  "CIERRE": "MANUAL",
  "VELTRIX es una herramienta de registro y no constituye asesoramiento financiero ni recomendación de inversión. Operar implica riesgo de pérdida y los resultados pasados no garantizan resultados futuros. No está afiliado a TradingView.": "VELTRIX is a record-keeping tool and is not financial advice or an investment recommendation. Trading involves risk of loss and past results do not guarantee future results. Not affiliated with TradingView.",
  "No se pudo marcar TP.": "Couldn't mark TP.",
  "No se pudo marcar SL.": "Couldn't mark SL.",
  "No se pudo reabrir.": "Couldn't reopen.",
  "CALCULADORA DE RIESGO": "RISK CALCULATOR",
  "Cuánto operar para no perder más de lo que decidiste.": "How much to trade so you don't lose more than you decided.",
  "TU CUENTA": "YOUR ACCOUNT",
  "LA OPERACIÓN": "THE TRADE",
  "RESULTADO": "RESULT",
  "CANTIDAD A OPERAR": "AMOUNT TO TRADE",
  "Copiar cantidad": "Copy amount",
  "CAPITAL ($)": "CAPITAL ($)",
  "RIESGO (%)": "RISK (%)",
  "APALANCAMIENTO (x)": "LEVERAGE (x)",
  "COMISIÓN (%)": "FEE (%)",
  "opcional": "optional",
  "Arriesgás": "You risk",
  "Valor de la posición": "Position value",
  "Margen necesario": "Margin needed",
  "Distancia al stop": "Distance to stop",
  "Comisiones estimadas": "Estimated fees",
  "Ganás si toca el TP": "You gain if TP is hit",
  "Riesgo : beneficio": "Risk : reward",
  "Completá capital, riesgo, entrada y stop loss para ver cuánto operar.": "Fill in capital, risk, entry and stop loss to see how much to trade.",
  "Cálculo orientativo. Verificá siempre los valores en tu plataforma antes de operar.": "Estimate only. Always verify the values on your platform before trading.",
  "Las notificaciones no funcionan en emuladores: probá en un celular real.": "Notifications don't work on emulators: try on a real phone.",
  "Las notificaciones están bloqueadas. Activalas en Ajustes del celular → Apps → VELTRIX → Notificaciones.": "Notifications are blocked. Turn them on in your phone's Settings → Apps → VELTRIX → Notifications.",
  "Falta el identificador del proyecto Expo en la configuración de la app.": "The Expo project ID is missing from the app configuration.",
  "Falta configurar Firebase (FCM) en esta versión de la app. Detalle: ": "Firebase (FCM) isn't set up in this version of the app. Details: ",
  "No se pudo obtener el permiso de envío: ": "Couldn't get permission to send: ",
  "No se pudo guardar este celular en tu cuenta: ": "Couldn't save this phone to your account: ",
  "Notificaciones activas en este celular.": "Notifications are active on this phone.",
  "✅ VELTRIX funciona": "✅ VELTRIX works",
  "Así te vamos a avisar cuando llegue una señal.": "This is how we'll notify you when a signal arrives.",
  "Enviada. Si en unos segundos no aparece, la configuración de Firebase en Expo está incompleta.": "Sent. If it doesn't show up in a few seconds, the Firebase setup in Expo is incomplete.",
  "Expo no tiene las credenciales de Firebase (FCM V1) de este proyecto. Hay que subirlas en expo.dev → Credentials.": "Expo doesn't have this project's Firebase (FCM V1) credentials. Upload them at expo.dev → Credentials.",
  "No se pudo enviar: ": "Couldn't send: ",
  "respuesta inesperada de Expo": "unexpected response from Expo",
  "No se pudo conectar con Expo: ": "Couldn't connect to Expo: ",
  "Listo": "Done",
  "Revisá el riesgo": "Check the risk",
  "El riesgo por operación no puede pasar de 100 %.": "Risk per trade can't exceed 100%.",
  "Capital guardado. Ahora ves tus resultados también en dinero.": "Capital saved. You now see your results in money too.",
  "La URL actual dejará de funcionar. Vas a tener que actualizarla en tus alertas de TradingView.": "The current URL will stop working. You'll have to update it in your TradingView alerts.",
  "Regenerar": "Regenerate",
  "Se borran tu cuenta y todos tus datos (operaciones, webhook y dispositivos) de forma permanente. No se puede deshacer.": "Your account and all your data (trades, webhook and devices) will be permanently deleted. This can't be undone.",
  "Eliminar todo": "Delete everything",
  "VELTRIX diario.csv": "VELTRIX journal.csv",
  "Borrar todo el diario": "Clear the whole journal",
  "Se eliminan todas tus operaciones (también en la web). No se puede deshacer.": "All your trades will be deleted (on the web too). This can't be undone.",
  "Borrar todo": "Clear everything",
  "No se pudo borrar.": "Couldn't clear.",
  "CAPITAL Y DINERO": "CAPITAL AND MONEY",
  "Balance": "Balance",
  "resultado": "result",
  "Cargá tu capital y el % que arriesgás por operación para ver tus resultados en dinero, no solo en R.": "Enter your capital and the % you risk per trade to see your results in money, not just in R.",
  "CAPITAL": "CAPITAL",
  "MONEDA": "CURRENCY",
  "1R equivale a": "1R equals",
  "Guardar capital": "Save capital",
  "Es una estimación: multiplica tus R por lo que arriesgás. Las tarjetas para compartir siguen mostrando solo R.": "It's an estimate: it multiplies your R by what you risk. Share cards still show R only.",
  "LÍMITES DIARIOS": "DAILY LIMITS",
  "Hoy": "Today",
  "PÉRDIDA MÁX. (R)": "MAX. LOSS (R)",
  "OPERACIONES MÁX.": "MAX. TRADES",
  "ej: 3": "e.g. 3",
  "ej: 5": "e.g. 5",
  "Guardar límites": "Save limits",
  "Dejá un campo vacío para no usar ese límite. Te avisamos al llegar al 80 % y cuando lo alcanzás.": "Leave a field empty to skip that limit. We warn you at 80% and when you reach it.",
  "NOTIFICACIONES": "NOTIFICATIONS",
  "Revisando…": "Checking…",
  "Revisar": "Check",
  "Enviar prueba": "Send test",
  "CUENTA": "ACCOUNT",
  "Cerrar sesión": "Sign out",
  "Eliminar mi cuenta y mis datos": "Delete my account and data",
  "CIERRE AUTOMÁTICO": "AUTO-CLOSE",
  "VELTRIX sigue el precio y marca TP o SL solo cuando el precio los toca (criptomonedas). Si una misma vela toca ambos, se toma SL. Podés apagarlo si preferís cerrar a mano.": "VELTRIX follows the price and marks TP or SL only when the price hits them (crypto). If one candle hits both, SL is used. You can turn it off if you prefer to close by hand.",
  "DATOS": "DATA",
  "Exportar diario (CSV)": "Export journal (CSV)",
  "Enviá tus señales a esta URL, vengan de donde vengan (TradingView con webhooks, Zapier, Make, n8n, bots propios). Si recibís señales por Telegram o WhatsApp, pegá el mensaje en Registrar → Pegar señal.": "Send your signals to this URL, wherever they come from (TradingView with webhooks, Zapier, Make, n8n, your own bots). If you get signals on Telegram or WhatsApp, paste the message in Log → Paste signal.",
  "Copiar URL": "Copy URL",
  "ARMADOR DE ALERTAS": "ALERT BUILDER",
  "LEGAL": "LEGAL",
  "Términos de uso": "Terms of use",
  "Política de privacidad": "Privacy policy",
  "Eliminación de datos": "Data deletion",
  "IDIOMA": "LANGUAGE",
  "No disponible": "Not available",
  "Este dispositivo no permite compartir imágenes desde la app.": "This device doesn't allow sharing images from the app.",
  "Compartir mi resultado": "Share my result",
  "No se pudo compartir la imagen.": "Couldn't share the image.",
  "Diario de trading": "Trading journal",
  "ACIERTO": "WIN RATE",
  "MEJOR": "BEST",
  "Llevá tu diario de trading con VELTRIX": "Keep your trading journal with VELTRIX",
  "Resultados pasados no garantizan resultados futuros. No es asesoramiento financiero.": "Past results do not guarantee future results. Not financial advice.",
  "Compartir imagen": "Share image",
  "Solo muestra resultados en R: sin montos de dinero ni datos de tu cuenta.": "Shows results in R only: no money amounts or account data.",
  "7 días": "7 days",
  "Este mes": "This month",
  "Todo": "All",
  "Abiertas": "Open",
  "Últimas 30": "Last 30",
  "SIN SEÑALES ABIERTAS": "NO OPEN SIGNALS",
  "AÚN NO HAY SEÑALES": "NO SIGNALS YET",
  "Cuando llegue una alerta de TradingView aparece acá con una notificación. También podés cargarla a mano desde la pestaña Registrar.": "When a TradingView alert arrives it shows up here with a notification. You can also enter it by hand from the Log tab.",
  "Todas": "All",
  "Ganadas": "Won",
  "Perdidas": "Lost",
  "↗ Compartir mi resultado": "↗ Share my result",
  "HISTORIAL": "HISTORY",
  "SIN OPERACIONES CERRADAS": "NO CLOSED TRADES",
  "Cuando marques TP, SL o un cierre manual en una señal, queda registrada acá.": "When you mark TP, SL or a manual close on a signal, it's recorded here.",
  "Cantidad copiada.": "Amount copied.",
  "No se pudo copiar automáticamente.": "Couldn't copy automatically.",
  "Cuánto operar para no perder más de lo que decidiste": "How much to trade so you don't lose more than you decided",
  "Capital ($)": "Capital ($)",
  "Riesgo (%)": "Risk (%)",
  "Apalancamiento (x)": "Leverage (x)",
  "Comisión (%)": "Fee (%)",
  "Stop loss": "Stop loss",
  "compra": "buy",
  "venta": "sell",
  "Cantidad a operar": "Amount to trade",
  "PROFIT FACTOR": "PROFIT FACTOR",
  "MEJOR OPERACIÓN": "BEST TRADE",
  "Imagen descargada.": "Image downloaded.",
  "Mi resultado en VELTRIX": "My result on VELTRIX",
  "Descargar": "Download",
  "La imagen muestra solo resultados en R: no incluye montos de dinero ni datos de tu cuenta.": "The image shows results in R only: it includes no money amounts or account data.",
  "operación cerrada": "closed trade",
  "operaciones cerradas": "closed trades",
  "Próximamente en Google Play": "Coming soon on Google Play",
  "PRÓXIMAMENTE EN": "COMING SOON ON",
  "CURVA DE CAPITAL": "EQUITY CURVE",
  "R acumulado por operación cerrada": "Cumulative R per closed trade",
  "Todavía no hay operaciones cerradas. Cuando marques un TP, un SL o un cierre manual,": "No closed trades yet. When you mark a TP, an SL or a manual close,",
  "la": "the",
  "curva de capital en R": "equity curve in R",
  "se dibuja acá.": "is drawn here.",
  "Rendimiento por mes calendario": "Performance by calendar month",
  "Mes": "Month",
  "Ops": "Trades",
  "% acierto": "% win rate",
  "R neto": "Net R",
  "Total": "Total",
  "Dónde ganás y dónde perdés": "Where you win and where you lose",
  "R neto por grupo y cantidad de operaciones cerradas. Usá los consejos con cuidado si son pocas operaciones.": "Net R per group and number of closed trades. Use the tips with care when there are few trades.",
  "Qué te suma y qué te resta": "What adds to you and what costs you",
  "Cuidado con tu límite diario": "Watch your daily limit",
  "Disciplina: frená antes de que sea tarde": "Discipline: stop before it's too late",
  "Resultado de hoy": "Today's result",
  "Operaciones de hoy": "Today's trades",
  "Pérdida máx. (R)": "Max. loss (R)",
  "Operaciones máx.": "Max. trades",
  "Tus resultados en dinero, no solo en R": "Your results in money, not just in R",
  "Resultado": "Result",
  "Cargá tu capital y cuánto arriesgás por operación para ver tu balance y tus resultados en dinero.": "Enter your capital and how much you risk per trade to see your balance and results in money.",
  "Capital inicial": "Starting capital",
  "Moneda": "Currency",
  "Completá capital y riesgo para calcular cuánto vale 1R.": "Fill in capital and risk to calculate what 1R is worth.",
  ": es lo que perdés si una operación toca el stop.": ": that's what you lose if a trade hits the stop.",
  "El dinero se calcula multiplicando tus R por el valor de 1R (riesgo fijo sobre el capital inicial). Es una estimación: no incluye comisiones ni deslizamiento.": "Money is calculated by multiplying your R by the value of 1R (fixed risk on the starting capital). It's an estimate: it doesn't include fees or slippage.",
  "Mensaje de alerta copiado.": "Alert message copied.",
  "Armador de alertas": "Alert builder",
  "Funciona con cualquier indicador. Elegí la dirección y escribí en TP y SL lo que tu indicador entrega": "Works with any indicator. Choose the direction and type in TP and SL what your indicator provides",
  "un": "a",
  "de TradingView o un número fijo). Después copiá el mensaje en el campo \"Mensaje\" de la alerta.": "from TradingView or a fixed number). Then copy the message into the alert's \"Message\" field.",
  "Sin TP/SL de un indicador, escribí números fijos. Si tu indicador no expone TP/SL, hará falta una alerta de": "Without TP/SL from an indicator, type fixed numbers. If your indicator doesn't expose TP/SL, you'll need a",
  "que los incluya.": "alert that includes them.",
  "EL DIARIO ESTÁ VACÍO": "THE JOURNAL IS EMPTY",
  "Pegá una alerta del indicador": "Paste an alert from the",
  "en el panel de registro, cargá tu primera operación manual, o explorá la app con datos de ejemplo.": "indicator into the log panel, enter your first trade manually, or explore the app with sample data.",
  "LIBRO DE OPERACIONES": "TRADE BOOK",
  "de": "of",
  "en pantalla": "shown",
  "Más recientes": "Newest first",
  "Más antiguas": "Oldest first",
  "Mejor R primero": "Best R first",
  "Peor R primero": "Worst R first",
  "Buscar activo…": "Search asset…",
  "LONG y SHORT": "LONG and SHORT",
  "Solo LONG": "LONG only",
  "Solo SHORT": "SHORT only",
  "Todos los estados": "All statuses",
  "En Break Even": "At Break Even",
  "Todos los meses": "All months",
  "Limpiar": "Clear",
  "Ninguna operación coincide con los filtros.": "No trades match the filters.",
  "Limpiar filtros": "Clear filters",
  "Dir": "Dir",
  "Acciones": "Actions",
  "Marcar Take Profit": "Mark Take Profit",
  "Marcar Stop Loss": "Mark Stop Loss",
  "Cierre manual (parcial / break even)": "Manual close (partial / break even)",
  "Reabrir operación": "Reopen trade",
  "¿Borrar?": "Delete?",
  "Eliminar": "Delete",
  "Etiqueta propia": "Custom tag",
  "Cierre manual": "Manual close",
  "Confirmar cierre": "Confirm close",
  "En TP": "At TP",
  "En SL": "At SL",
};
